package main

var (
	START                  = 0
	REGISTER_ENTER_EMAIL   = 1
	REGISTER_ENTER_LOGIN   = 2
	REGISTER_ENTER_PASS    = 3
	SIGNIN_ENTER_LOGIN     = 4
	SIGNIN_ENTER_PASSWORD  = 5
	TASK_SEND_TITLE        = 6
	TASK_SEND_DEADLINE     = 7
	TASK_SEND_DURATION     = 8
	TASK_SEND_PRIORITY     = 9
	TASK_MENU              = 10
	GOT_ALL_TASK           = 11
	USER_MENU              = 12
	UPDATE_USER_EMAIL      = 13
	UPDATE_APPROVED        = 14
	GOT_TITLE 			   = 15
	ASKED_DEADLINE 		   = 16
	ASKED_DURATION 		   = 17
	ASKED_PRIORITY   	   = 18
	UPDATE_USER_LOGIN 	   = 19
	UPDATE_USER_FULLNAME   = 20
	UPDATE_USER_PASS       = 21
	GROUP_SEND_TITLE       = 22
	GROUP_SEND_DESCRIPTION = 23
	GROUP_MENU             = 24
	GROUP_SEND_ID          = 25
	GROUP_DELETE           = 26
	GROUP_SEND_NEW_ID      = 27
	GROUP_SEND_NEW_TITLE   = 28
	GROUP_SEND_DESC_ID     = 29
	GROUP_SEND_NEW_DESC    = 30
)
