package main

var (
	START = 0
	REGISTER_ENTER_EMAIL = 1
	REGISTER_ENTER_LOGIN = 2
	REGISTER_ENTER_PASS = 3
	SIGNIN_ENTER_LOGIN = 4
	SIGNIN_ENTER_PASSWORD = 5
	TASK_SEND_TITLE = 6
	TASK_SEND_DEADLINE = 7
	TASK_SEND_DURATION = 8
	TASK_SEND_PRIORITY = 9
	MENU = 10
)
